In [13]:
#Question 1
class Employee:
  # data member to count the number of employees
  no_of_employees = 0
  def __init__(self,name,family,salary,department):
    self.name = name
    self.family = family
    self.salary = salary
    self.department = department
    Employee.no_of_employees += 1

  def average_salary(employees):
    if len(employees) == 0:
      return 0
    sum = 0
    for employee in employees:
      sum += employee.salary
    return sum / len(employees)

class FullTimeEmployee(Employee):
  def __init__(self,name,family,salary,department):
    super().__init__(name,family,salary,department)

# Create instances of Employee and FulltimeEmployee
e1=Employee('John','Smith',40000,'IT')
e2=Employee('Luca','green',90000,'Finance')
fe1=FullTimeEmployee('Bob','Builder',70000,'civil')
fe2=FullTimeEmployee('Oswald','Blue',40000,'HR')

# List of all employees
employees = [e1,e2,fe1,fe2]

# Print details of all employees
for emp in employees:
    print(f"Name: {emp.name}, Family: {emp.family}, Salary: {emp.salary}, Department: {emp.department}")

# List of all full time employees
Full_time_employees = [fe1,fe2]

# Print total number of employees
print("Total number of employees:", Employee.no_of_employees)

# Calculate and print average salary of all employees
avg_salary = Employee.average_salary(employees)
print("Average Salary of all employees is:", avg_salary)

# Calculate and print average salary of full time employees
Fe_avg_salary = FullTimeEmployee.average_salary(Full_time_employees)
print("Average Salary of full time employees is:", Fe_avg_salary)


Name: John, Family: Smith, Salary: 40000, Department: IT
Name: Luca, Family: green, Salary: 90000, Department: Finance
Name: Bob, Family: Builder, Salary: 70000, Department: civil
Name: Oswald, Family: Blue, Salary: 40000, Department: HR
Total number of employees: 4
Average Salary of all employees is: 60000.0
Average Salary of full time employees is: 55000.0


In [17]:
#Question 2
import numpy as np

#Create a random vector of size 20 with float in the range 1-20
vector=np.random.uniform(1,20, size=20)
print("Initial vector:\n",vector)

#Reshape the array to 4 by 5
reshaped_vector=vector.reshape(4,5)
print("\nReshaped array:\n",reshaped_vector)

#Replace the max in each row with 0 without using a for loop
max_indices = np.argmax(reshaped_vector, axis=1)  # Find max indices in each row
rows = np.arange(reshaped_vector.shape[0])        # get the row indices
reshaped_vector[rows,max_indices] = 0             # Replace max elements with 0
print("\nArray after replacing max in each row with 0:\n",reshaped_vector)

Initial vector:
 [12.91594629  3.09700303  9.66076448  6.21214126 15.17562587  6.50113064
 11.43031213 16.06979422  1.66132463 14.01952415 15.80836071 19.44797623
  3.72831976 11.23920843 10.04602908  6.61946178  7.89187558  8.98697361
 11.51410259 19.90168081]

Reshaped array:
 [[12.91594629  3.09700303  9.66076448  6.21214126 15.17562587]
 [ 6.50113064 11.43031213 16.06979422  1.66132463 14.01952415]
 [15.80836071 19.44797623  3.72831976 11.23920843 10.04602908]
 [ 6.61946178  7.89187558  8.98697361 11.51410259 19.90168081]]

Array after replacing max in each row with 0:
 [[12.91594629  3.09700303  9.66076448  6.21214126  0.        ]
 [ 6.50113064 11.43031213  0.          1.66132463 14.01952415]
 [15.80836071  0.          3.72831976 11.23920843 10.04602908]
 [ 6.61946178  7.89187558  8.98697361 11.51410259  0.        ]]
